#services:
#    ms_gestion_biblio_user.example:
#        class: MS\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
services:
    g2_ms_user:
        class: MS\UserBundle\EventListener\SecurityListener
#        arguments: ["@security.context"]
#
#        tags:
#            - { }