ms_user:
    resource: "@MSUserBundle/Controller/"
    type:     annotation
    prefix:   /

g2_ms_gestionBibliotheque:
    resource: "@MSGestionBibliothequeBundle/Resources/config/routing.yml"
    prefix:   /
login:
    path: /login
    defaults:
        _controller: MSUserBundle:Security:login
login_check:
    path: /login_check
logout:
    path: /logout
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin
