ms_user:
    resource: "@MSUserBundle/Controller/"
    type:     annotation
    prefix:   /

g2_ms_gestionBibliotheque:
    resource: "@MSGestionBibliothequeBundle/Resources/config/routing.yml"
    prefix:   /
login:
    path: /login
    defaults:
        _controller: MSUserBundle:Security:login
login_check:
    path: /login_check
logout:
    path: /logout
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile