ms_gestion_biblio_user:
    resource: "@MSGestionBiblioUserBundle/Controller/"
    type:     annotation
    prefix:   /

oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform
g2_ms_gestionBibliotheque:
    resource: "@MSGestionBibliothequeBundle/Resources/config/routing.yml"
    prefix:   /
login:
    path: /login
    defaults:
        _controller: MSGestionBiblioUserBundle:Security:login
login_check:
    path: /login_check
logout:
    path: /logout
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin
