g2_ms_gestion_bibliotheque_home:
    path:     /{page}
    defaults:
        _controller: MSGestionBibliothequeBundle:Oeuvre:index
        page: 1
    requirements:
        _format: html
        page: \d*
        
g2_ms_gestion_bibliotheque_auteur_view:
    path:      /auteur/{id}
    defaults:
        _controller: MSGestionBibliothequeBundle:Auteur:view
    requirements:
        _format: html
        id: \d+

g2_ms_gestion_bibliotheque_livre_view:
    path:      /livre/{id}
    defaults:
        _controller: MSGestionBibliothequeBundle:Livre:view
    requirements:
        _format: html
        id: \d+
        
g2_ms_gestion_bibliotheque_livre_find:
    path:      /livre/find
    defaults:
        _controller: MSGestionBibliothequeBundle:Livre:find
    requirements:
        _format: html
        
g2_ms_gestion_bibliotheque_dvd_view:
    path:      /dvd/{id}
    defaults:
        _controller: MSGestionBibliothequeBundle:DVD:view
    requirements:
        _format: html
        id: \d+
        
g2_ms_gestion_bibliotheque_dvd_find:
    path:      /dvd/find
    defaults:
        _controller: MSGestionBibliothequeBundle:DVD:find
    requirements:
        _format: html

g2_ms_gestion_bibliotheque_emprunts_index:
    path:      /emprunt/
    defaults:
        _controller: MSGestionBibliothequeBundle:Emprunt:index
    requirements:
        _format: html
    
g2_ms_gestion_bibliotheque_emprunts_view:
    path:      /emprunt/{id}
    defaults:
        _controller: MSGestionBibliothequeBundle:Emprunt:view
    requirements:
        _format: html
        id: \d+
    
g2_ms_gestion_bibliotheque_emprunts_add:
    path:      /emprunt/add/{id}
    defaults:
        _controller: MSGestionBibliothequeBundle:Emprunt:add
    requirements:
        _format: html
        id: \d+
        
g2_ms_gestion_bibliotheque_adherent:
    resource: "@MSGestionBibliothequeBundle/Resources/config/routing/adherent.yml"
    prefix:   /adherent
        
g2_ms_gestion_bibliotheque_reservations:
    resource: "@MSGestionBibliothequeBundle/Resources/config/routing/reservations.yml"
    prefix:   /reservation

g2_ms_gestion_bibliotheque_gestionnaire:
    resource: "@MSGestionBibliothequeBundle/Resources/config/routing/gestionnaire.yml"
    prefix:   /gestionnaire
