services:
    _defaults:
        autowire: true
        autoconfigure: true
    artwork.provider:
        class: MS\GestionBibliothequeBundle\DataFixtures\Faker\Provider\ArtworkProvider
        tags:
            -  { name: h4cc_alice_fixtures.provider }
#    form.type.datePicker:
#        class:  MS\GestionBibliothequeBundle\Form\Type\DatePickerType
#        tags:
#           - { name: form.type, alias: datePicker }
#        autowire: true
#        public: true
    cov.twig.class_test:
        class: MS\GestionBibliothequeBundle\Twig\ClassTestExtension
        public: true
        autowire: true
        tags:
            - { name: twig.extension }